version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  spurredis:
    build: .
    environment:
      SPUR_REDIS_API_TOKEN: ${SPUR_REDIS_API_TOKEN}
      SPUR_REDIS_CHUNK_SIZE: 5000
      SPUR_REDIS_CONCURRENT_NUM: 4
      SPUR_REDIS_ADDR: redis:6379